#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x14706DBE1E4B4540 (fourdan@xfce.org)
#
Name     : xorg-server
Version  : 21.1.6
Release  : 208
URL      : https://www.x.org/releases/individual/xserver/xorg-server-21.1.6.tar.gz
Source0  : https://www.x.org/releases/individual/xserver/xorg-server-21.1.6.tar.gz
Source1  : https://www.x.org/releases/individual/xserver/xorg-server-21.1.6.tar.gz.sig
Summary  : Modular X.Org X Server
Group    : Development/Tools
License  : MIT
Requires: xf86-input-libinput
Requires: xf86-video-amdgpu
Requires: xf86-video-ati
Requires: xf86-video-fbdev
Requires: xf86-video-nouveau
Requires: xf86-video-vesa
Requires: xwayland
BuildRequires : bison
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : doxygen
BuildRequires : flex
BuildRequires : font-util-dev
BuildRequires : freetype-dev
BuildRequires : graphviz
BuildRequires : libdmx-dev
BuildRequires : libgcrypt-dev
BuildRequires : libxshmfence-dev
BuildRequires : libxslt-bin
BuildRequires : nettle-dev
BuildRequires : pkgconfig(dri2proto)
BuildRequires : pkgconfig(dri3proto)
BuildRequires : pkgconfig(epoxy)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glproto)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(libxcvt)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(udev)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xau)
BuildRequires : pkgconfig(xcb-aux)
BuildRequires : pkgconfig(xcb-composite)
BuildRequires : pkgconfig(xcb-keysyms)
BuildRequires : pkgconfig(xcb-xfixes)
BuildRequires : pkgconfig(xdmcp)
BuildRequires : pkgconfig(xf86dgaproto)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xfont)
BuildRequires : pkgconfig(xfont2)
BuildRequires : pkgconfig(xkbcomp)
BuildRequires : pkgconfig(xkbfile)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xshmfence)
BuildRequires : wayland-dev
BuildRequires : wayland-protocols-dev
BuildRequires : xmlto
BuildRequires : xtrans-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-add-default-keyboard-setup-for-xorg.patch
Patch2: xorg-git-update.patch

%description
This is a submodule to access linux framebuffer devices.
It is supported to work as helper module (like vgahw)
for the chipset drivers.  There are functions for
saving/restoring/setting video modes, set palette entries,
and a few more helper functions.  Some of them can be
hooked directly into ScrnInfoRec.

%prep
%setup -q -n xorg-server-21.1.6
cd %{_builddir}/xorg-server-21.1.6
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1674769715
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export CFLAGS="-O3 -g -fopt-info-vec "
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static --with-int10=x86emu \
--enable-config-udev \
--enable-config-udev-kms \
--enable-dri2 \
--enable-dri \
--enable-dri3 \
--enable-dbe \
--enable-record \
--enable-systemd-logind \
--enable-glamor \
--disable-xwayland
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1674769715
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xorg-server
cp %{_builddir}/xorg-server-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xorg-server/11d1ae389a1a78f7832586e4c2a0c3c7263b7475 || :
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/Xwayland
## install_append content
mkdir -p %{buildroot}/usr/share/defaults/etc/X11/xorg.conf.d/
cp 00-keyboard.conf %{buildroot}/usr/share/defaults/etc/X11/xorg.conf.d/
## install_append end

%files
%defattr(-,root,root,-)
